- aider/coder.py
- tests/test_coder.py
Fixes issue #11 where openai chat completion was raising a conn reset error.
> Handle openai exceptions

- aider/coder.py
- aider/main.py
- aider/utils.py
- tests/test_utils.py
Added:   --openai-api-base OPENAI_API_BASE
Specify the OpenAI API base endpoint (default: https://api.openai.com/v1)
[env var: AIDER_OPENAI_API_BASE]
> Added:  --openai-api-base OPENAI_API_BASE

- examples/add-test.md
> Fix typo in add-test.md

- aider/commands.py
- tests/test_commands.py
This should resolve the remaining problem reported in #57
> The /add command should recurse into named subdirs per issue #57

- aider/coders/wholefile_coder.py
- tests/test_wholefile.py
Based on the GPT-3.5 response in issue #73.
> Prioritize how to allocate code blocks to filenames in wholefile

- aider/coders/base_coder.py
- aider/main.py
- docs/faq.md
- tests/test_coder.py
- tests/test_commands.py
- tests/test_editblock.py
- tests/test_wholefile.py
Per request and discussion in #50.
> Added args to configure openai module to access Azure

- aider/commands.py
> disabling GIT_EDITOR when calling /git

- aider/coders/base_coder.py
- aider/history.py
fix #231
I'm not sure how the error was occuring and wasn't able to reproduce it locally but this should handle it better
> small fix for better error handling if the summarizer ever fails

- benchmark/Dockerfile
- benchmark/benchmark.py
Also added a small change to avoid having to manually set the git safe directory
> Fix benchmark model creation to work with v14

- .gitignore
- README.md
- docs/faq.md
Added some instructions for running the project locally.
> Added instructions for running the project locally. 

- benchmark/README.md
Providing a fix for https://github.com/paul-gauthier/aider/issues/369
> Use expected exercism-python destination

- aider/main.py
Fixes https://github.com/paul-gauthier/aider/issues/374
> Fixes #374 - logging add_to_input_history if args.message is used.

- .github/workflows/ubuntu-tests.yml
- .github/workflows/windows-tests.yml
- dev-requirements.txt
- docs/install.md
- requirements.txt
> Bump all dependencies, to pick up py-tree-sitter-languages 1.9.1 with python 3.12 support

- aider/coders/base_coder.py
- aider/coders/wholefile_prompts.py
- aider/commands.py
- aider/main.py
- aider/models.py
> New /model command to switch models, /models to search them

- aider/args.py
- aider/coders/base_coder.py
- aider/history.py
- aider/main.py
> Restore prior chat history on launch

- aider/commands.py
> Fix issue with aider --commit

- aider/commands.py
> minor: remove unnecessary return

- .gitignore
Add .DS_Store, .vscode/, and aider.code-workspace to .gitignore.
> Ignore MacOS and VSCode detritus.

- website/docs/scripting.md
Hi Paul, thanks for the great tool. I was reading through the docs and saw a small typo so figured I'd send a quick PR.
> Fix tiny typo

- aider/commands.py
Displays files in chat AFTER files not in chat.
This is helpful for big repositories where it consist mostly of files NOT in chat.
```md
src/dev_utils/summarize_code.py
src/formatters/__init__.py
src/formatters/debug_formatters.py
src/formatters/langdspy_formatters.py
src/formatters/rag_formatters.py
src/formatters/slack_formatters.py
src/lib/__init__.py
src/lib/collection_lib.py
src/lib/discount_lib.py
src/lib/keyword_lib.py
src/lib/listing_analysis_lib.py
src/lib/nosto_lib.py
src/lib/page_lib.py
src/lib/pgvector_lib.py
src/lib/pgvector_reconnect.py
src/lib/plot_colors.py
src/lib/product_lib.py
src/lib/rag_lib.py
src/lib/related_object_lib.py
src/lib/shopify_lib.py
src/lib/sitemap_lib.py
src/lib/slack_file_lib.py
src/lib/slack_thread_dispatcher.py
src/lib/summary_lib.py …
```
> Reordered the output of files in chat and repo to improve readability.

- aider/website/docs/usage/tips.md
Just a small hint which hopefully helps newcomers.
> Update tips.md with hint for creating new files

- aider/models.py
- aider/website/docs/llms/cohere.md
This PR adds new Cohere models with [better code and reasoning capabilities](https://docs.cohere.com/changelog/command-gets-refreshed).
> Add New Cohere Models

- aider/website/_data/edit_leaderboard.yml
Greetings! I got Codestral-22B running locally via LMStudio, and managed to run the benchmarks on it. These are the results. I was surprised at how poorly it performed. Maybe it would do better with the diff format. Cheers!
> Add benchmark results for Codestral-22B (whole)

- aider/coders/base_coder.py
- aider/commands.py
> feat: include non-repo files for completing /read

- aider/website/_data/edit_leaderboard.yml
Added ollama/codestral benchmark
> Benchmark: ollama/codestral

- aider/args.py
> doc: clarify soft limit for chat history tokens

- aider/args.py
- aider/website/assets/sample.aider.conf.yml
- aider/website/assets/sample.env
- aider/website/docs/config/aider_conf.md
- aider/website/docs/config/dotenv.md
- aider/website/docs/config/options.md
Fix for the documentation fix :)
Sorry for the oversight.
> doc: fix wrong encapsulation

- aider/models.py
> fix: correct weak model names for Sonnet-3.5 on OpenRouter

- aider/args.py
> cleanup: remove unreachable return statements

- aider/website/_data/edit_leaderboard.yml
Hello, we have also evaluated Qwen2.5-Coder-32B-Instruct using the diff format. This commit updates the evaluation results.
> Add diff format evaluation results of Qwen2.5-Coder-32B-Instruct.

- aider/io.py
Resolve issue where Aider fails to write multiple, consecutive changes to a single file due to Visual Studio briefly locking a file for writing after it was edited. Presumably VS is doing some sort of processing, such as for IntelliSense, behind the scenes. This solution is applicable to other, similar editor/IDE behaviors.
> Added io.py write_text exponential backoff to gracefully handle transient file locks

- aider/website/_data/quant.yml
mlx Qwen2.5-Coder-32B-Instruct-4bit added to quant blog
> mlx Qwen2.5-Coder-32B-Instruct-4bit added to quant blog

- aider/website/_data/quant.yml
- aider/website/_posts/2024-11-21-quantization.md
quants and article updated. pass rate is better, but there are more errors in responses.
> MLX 4bit and 8bit diff added

- aider/main.py
A pedantic change, but it annoyed me slightly.
> Rephrase home dir warning

- aider/main.py
Fixes https://github.com/Aider-AI/aider/issues/772
> Disable streamlit email prompt

- aider/linter.py
- aider/run_cmd.py
- tests/basic/test_linter.py
> fix: lint command with nested spaced strings

- aider/website/docs/llms.md
- aider/website/docs/usage/caching.md
This pull request includes updates to the documentation for supported language models and prompt caching. The most important changes include updating the name of a supported model and clarifying the caching capabilities of different models.
Updates to supported language models:
* [`aider/website/docs/llms.md`](diffhunk://#diff-a5b6f0254daebec7f6f84707731f5870df119c962bc35d988cc08f293246feceL22-R22): Updated the name of "DeepSeek Coder V2" to "DeepSeek V3" to reflect the latest version.
Clarifications on prompt caching:
* [`aider/website/docs/usage/caching.md`](diffhunk://#diff-3d8b12ed74f723d5886b57a9914ab54fc0c0a89fe61e9b57072b54aff9fedb64L7-R13): Clarified that DeepSeek provides caching for "Chat" instead of "Coder".
* [`aider/website/docs/usage/caching.md`](diffhunk://#diff-3d8b12ed74f7 …
> docs: clean DeepSeek Coder v2

- aider/editor.py
> subprocess called with shell true

- aider/website/docs/llms/ollama.md
This updates the doc with the new ENV variable ollama supports since [v0.5.13](https://github.com/ollama/ollama/releases/tag/v0.5.13)
> ollama: suggest higher minimum context length

- aider/watch.py
- tests/basic/test_watch.py
- tests/fixtures/watch.lisp
> Add support for Lisp-style comments in file watcher

- aider/io.py
Fixes: https://github.com/Aider-AI/aider/issues/3630
> Invoke the editor by pressing `C-x C-e`

- aider/queries/tree-sitter-languages/scala-tags.scm
- tests/basic/test_repomap.py
- tests/fixtures/languages/scala/test.scala
> feat: add repomap support for Scala

- aider/models.py
With this patch aider automatically supports all models available through openrouter. Also, it reports error if a model doesn't exist.
> OpenRouter models parameters fetching directly from their website

- .github/workflows/pre-commit.yml
- aider/coders/editblock_fenced_coder.py
- aider/coders/help_coder.py
- aider/linter.py
- benchmark/refactor_tools.py
- pyproject.toml
- scripts/30k-image.py
- scripts/dl_icons.py
- scripts/redact-cast.py
- tests/basic/test_watch.py
I see that this repository has a pre-commit configuration - nice!
So I add `pre-commit.yml`) to automate the execution of pre-commit hooks on pull requests and pushes.
Apparently it is not really used as there are quite some suggested changes.
Before updating the pre-commit configuration, I want to know if you are ok with applying pre-commit.
Exclusions can be added on the configuration to avoid checking certain files.
I can add the fixes/pre-commit configuration update to this PR or a separate one.
> ci: add pre-commit.yml for GitHub Actions

- aider/commands.py
> fix: Fix #3987 Pass the coder object to repo.commit

- aider/website/docs/faq.md
- aider/website/docs/scripting.md
Hi, this repo is awesome.
However when I was searching for some programatically usage, it is not that ​​eye-catching.
Finally I found this issue: https://github.com/Aider-AI/aider/issues/426 , and seems there was a hint before.
So I link scripting.md to faq, so that others can find it easily. Thx~  cc @paul-gauthier
> chore: prettier scripting usage for faq

- aider/website/_data/polyglot_leaderboard.yml
Add GPT-5 with high reasoning to polyglot leaderboard
> Add GPT-5 with all reasoning settings to polyglot leaderboard
