README.md

Add instructions for installing from source code to README

Add instructions for installing from source to README

---

aider/prompts.py

get rid of nonessential information that causes the prompt to be longer than needed
main system prompt: 924 chars -> 741 chars (183 chars saved)
system reminder prompt: 1304 chars -> 1168 chars (136 chars saved)
I have been using these prompts myself for some basic tasks and as far as I can tell so far, they perform basically the same.
However, since these improvements are only marginal compared to the size of code files inserted into the prompt, feel free to discard this PR without merging.

aider/prompts.py: reduce token size of prompts

---

aider/coders/base_coder.py
aider/main.py

The source code output in the chat will be colored in the given color scheme.
Syntax highlighting is powered by pygments, which supports many styles out of the box. For example:
- default (the default)
- dracula
- emacs
- github-dark
- monokai
- vim
- solarized-dark
- solarized-light
See https://pygments.org/styles/

Add program argument for syntax highlighting theme.

---

aider/coders/base_coder.py
aider/coders/editblock_coder.py
aider/coders/editblock_func_coder.py
aider/coders/single_wholefile_func_coder.py
aider/coders/wholefile_coder.py
aider/coders/wholefile_func_coder.py
aider/commands.py
aider/diffs.py
aider/io.py
aider/main.py
aider/repomap.py
aider/utils.py
tests/test_coder.py
tests/test_commands.py
tests/test_editblock.py
tests/test_repomap.py
tests/test_wholefile.py

Added --encoding cmd line arg
Catch unicode errors and gracefully report and handle them
Resolves issues #56 and #28

Use an explicit encoding to read/write text files, utf-8 by default

---

HISTORY.md
aider/coders/base_coder.py
aider/commands.py
aider/repomap.py
tests/test_coder.py

Also armors the code in various places to deal with unexpected failures to find/read files.
This should resolve issue #82.

Tell git not to quote filenames in ls-files, to handle unicode filenames

---

aider/commands.py

Handled the UnboundLocalError tat occurs when wrong prams are passed to the `/run` command

Handled Issue #114

---

aider/commands.py
tests/test_commands.py

Per #139 and #95, the `/add` command was failing if the cwd was not the same as the git root.

/add and /drop problems when cwd != git_root #139 #95

---

README.md
docs/commands.md

Added a section about the prompt-toolkit defaults. Note that the link in the README is to docs/commands.html which will be a dead link until aider.chat is rebuilt

More complete docs for prompt commands

---

HISTORY.md
aider/coders/base_coder.py
aider/coders/editblock_coder.py
aider/coders/editblock_func_coder.py
aider/coders/single_wholefile_func_coder.py
aider/coders/wholefile_coder.py
aider/coders/wholefile_func_coder.py
aider/commands.py
aider/main.py
aider/repo.py
docs/faq.md
tests/test_coder.py
tests/test_repo.py
tests/test_wholefile.py

Discussed in #200
If GPT tries to edit a dirty file, aider will just commit the dirty changes (with a nice message) before applying and committing GPT's edits.
You now never get interrupted and asked about pending dirty changes. Aider just commits them for you to keep them distinct from GPT's edits and preserve the ability to cleanly undo GPT's changes. And dirty changes are only ever committed by aider if the file is about to get modified by GPT.
As always, aider still respects the --no-dirty-commits flag. If set, it will apply GPT's edits without first committing dirty files.

Only commit dirty files if GPT tries to edit them #200

---

aider/coders/base_coder.py
aider/commands.py
aider/history.py
aider/main.py
aider/models/__init__.py
aider/models/model.py
aider/models/openai.py
aider/models/openrouter.py
aider/repo.py
aider/repomap.py
aider/sendchat.py
docs/faq.md
tests/test_models.py

Enabling aider to work with openrouter.ai as per #170 
If openai-api-base has openrouter.ai in it then it will use a different model class to instantiate and dynamically load the costs and max_tokens from the model list.
It works for all the manual testing I did but needs unit tests and more thorough testing, particularly of the chat summary feature and the finish_reason change (which openrouter api doesn't support).
Keen for feedback from @paul-gauthier on the approach taken before doing more work on tests and polish.

Openrouter compatibility

---

aider/coders/base_coder.py

completion.usage doesn't exist for non openai models

only show token costs if usage exists

---

aider/coders/base_coder.py
aider/main.py

Adding a `--skip-model-availability-check` flag to skip model availability check. 
This is needed to make Aider work with our internal Azure OpenAI proxy which does not fully support model check calls.

Add --skip-model-availability-check option

---

aider/main.py
tests/test_main.py

This commit introduces the `--message-file` flag to the `aider` tool, allowing users to specify a file containing the message to send to GPT. This feature processes the reply and then exits, disabling the chat mode. The implementation includes reading the content of the specified file and using it as the prompt message.
Additionally, a unit test has been added to `tests/test_main.py` to ensure the correct functionality of the `--message-file` flag. The test includes necessary mocks to handle non-interactive environments and verifies that the tool behaves as expected when a message file is provided.
This enhancement improves the usability of the `aider` tool for users who prefer or require non-interactive execution, such as in scripting or automated workflows.
Tested using:
```
docker …
```

Add `--message-file` flag and unit test

---

aider/repo.py

Discussed on Discord, traced down to the path Aider was checking to be cleaned not being normalized in the same way all other repo paths were.

Fix issue with path normalization that was causing files to be marked dirty on Windows when they were not

---

.github/workflows/docker-build-test.yml

Haven't been able to test this in my fork but maybe this will stop the docker action errors that seem omnipresent?
Maybe we could also just delete the docker action?

skip docker github action if credentials not present

---

aider/commands.py

This fixes issues with /run on Windows which usually manifested as encoding errors.
Sample: Error running command: 'charmap' codec can't decode byte 0x9d in position 298: character maps to <undefined>

Use encoding supplied to --encoding by default while running commands

---

aider/main.py

Adds option to skip the check for an update, better supports tooling which wants to do it's own update mechanism and not have aider print it out unconditionally.

fix https://github.com/paul-gauthier/aider/issues/452

---

aider/queries/tree-sitter-typescript-tags.scm
tests/test_repomap.py

Corrects the query syntax for Tree Sitter TypeScript. This causes correct repo maps to be created. E.g. for the [nodeadr](https://github.com/robogeek/nodeadr) project:
```text
lib/client.ts:
⋮...
│import { ADRConnection } from './oadr.js';
⋮...
│export type AddReportOptions = {
│
│    /**
│     * The quantity that is being measured (enums.MEASUREMENTS).
│     * Optional for TELEMETRY_STATUS reports.
│     */
│    measurement?: types.Measurement;
│
│    /**
│     * Whether you want the data to be collected incrementally
⋮...
│export class OpenADRClient {
│
│    /**
│     * Initializes a new OpenADR Client (Virtual End Node)
│     * 
│     * @param ven_name The name for this VEN
│     * @param ven_id The ID for this VEN. If you leave this blank,
│     *               a VEN_ID will be …
```

Typescript repo map fix

---

aider/args.py

This pull request updates the help text in the aider/args.py file to mention Anthropic instead of OpenAI for specifying the API key. This change ensures that the documentation is accurate and reflects the current usage of the API keys.
**Changes:**
• Updated the help text for the --anthropic-api-key argument to mention Anthropic instead of OpenAI.
**Files Modified:**
• aider/args.py

Update help text for specifying the API key to mention Anthropic instead of OpenAI

---

website/_data/edit_leaderboard.yml

Update data file for quantized local LLMs as in https://github.com/paul-gauthier/aider/issues/656
In `model` names, I removed `ollama/` prefix for consistency in leaderboard. (it still would be printed in `command` column)

Add quantized models in leaderboard: codeqwen, codestral, qwen2

---

aider/args.py
aider/main.py
aider/models.py
website/docs/install/optional.md
website/docs/options.md

When using local models, sometime the model definitions do not exist in litellm model registry. This change allows you to add a `.aider.model.json` file to your home director, the project directory or through a command line argument any file. The change will load in the following order
1. Home directory
2. git root
3. current directory
4. command line arg
litellm's documentation claims he `register_model` function will overwrite existing information so the files loaded last should take priority.

Allow models to be registered with litellm

---

README.md

There was a template typo in the Getting Started section of the README that I removed

doc: Removed template typo in README

---

.github/workflows/windows-tests.yml
.pre-commit-config.yaml
aider/args.py
aider/main.py
aider/tests/test_main.py
aider/utils.py

This PR addresses #630. I have left it in draft mode as I plan to add doc updates and perhaps some additional tests, but this is a first look.

All AIDER_* environment vars may now be placed within .env

---

aider/models.py

Fixes #700
(Note: using Copilot Workspace beta for grins. It wrote exactly what I wrote in my own temp fix last night, so that's something :smile:)
This pull request adds support for Vertex AI Claude models in `aider/models.py` by updating the `MODEL_SETTINGS` constant.
- Adds two new `ModelSettings` entries for `vertex_ai/claude-3-5-sonnet@20240620` and `vertex_ai/claude-3-opus@20240229` to handle the at-sign notation in model names.
- Configures `edit_format`, `weak_model_name`, `use_repo_map`, and `send_undo_reply` settings for the newly added Vertex AI Claude models to ensure they are correctly recognized and processed by the application.
NB: Current `litellm` will return an error related to calculating token costs for the haiku weak model. As of *this* PR, I have a …

Add support for vertex_ai/claude_* models

---

.github/workflows/ubuntu-tests.yml
.github/workflows/windows-tests.yml

Remove universal ctags install step from workflows as it's no longer used. There may be some other parts that still use it that would need further cleaning.

Remove universal ctags install from workflows

---

website/_includes/special-keys.md

noticed this is broken on the live documentation site

fix broken dotenv link in docs/config/aider_conf.html

---

aider/website/_data/edit_leaderboard.yml

Adding Gemma2-27b-q8 result to leaderboard for local LLM enthusiasts.
- Tested with `Ollama 0.2.1`
- `gemma2:27b-instruct-q8_0` model with hash `dab5dca674db`
This LLM model struggles with diff formatting; whole format works better.
The quality is not as good as rumored, at least for coding with Aider.
Those with high expectations might be disappointed.

Add Gemma2-27b-q8 benchmark result to leaderboard

---

aider/website/docs/install/install.md

"Py" confused me, it often refers to "PyInstaller"

Use "python" in windows install instructions

---

aider/models.py

Reverting token limit change for Vertex's Claude 3.5 sonnet as it does not yet support 8k token output:
```
BadRequestError: litellm.BadRequestError: AnthropicException - b'{"type":"error","error":{"type":"invalid_request_error","message":"max_tokens: 8192 > 4096, which is the maximum allowed number of output tokens for
claude-3-5-sonnet-20240620"}}'
```

Disable 8k token for vertex_ai/claude-3-5-sonnet

---

aider/commands.py

Small tweak to make it show read only files when I type ls;:
```
Read-only files:
setup.py
Files in chat:
scripts/update-docs.sh
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
scripts/update-docs.sh
>
```

feat: Add read-only files to the output of the 'ls' command

---

tests/basic/test_main.py

Use fake home directory to prevent `~/.aider.conf.yml` from affecting the test suite

---

aider/coders/editblock_func_coder.py
aider/commands.py
tests/basic/test_editblock.py

Clean up types and drop an unused variable

---

aider/coders/editblock_coder.py
tests/basic/test_editblock.py

This is a fix for https://github.com/paul-gauthier/aider/issues/1222. Currently, if you have an existing file and Aider tries to create a file with similar name, the new file doesn't get created since it's fuzzy-matched to an existing file [here](https://github.com/paul-gauthier/aider/blob/301c4265b76a5b8c4a939acb59314e091cacebec/aider/coders/editblock_coder.py#L532-L535)
This PR checks if edit block tries to create a new file and if so it passes `None` as `valid_fnames`

fix: Handle new file creation in the same folder

---

aider/website/_data/edit_leaderboard.yml

I ran the unquantised model via https://glhf.chat/ that serves HuggingFace models via vLLM (hence the `--openai-api-base` parameter in the `command`), and then I ran the `Q4_0` quantised model via Ollama (as of this PR, Ollama hasn't published the `Q8_0` quant, and I didn't feel like manually setting up the quant).

docs: add benchmark results for yi-coder 9b

---

aider/args.py
aider/website/docs/llms/anthropic.md
aider/website/docs/llms/azure.md
aider/website/docs/llms/bedrock.md
aider/website/docs/llms/cohere.md
aider/website/docs/llms/gemini.md
aider/website/docs/llms/groq.md
aider/website/docs/llms/openai.md
aider/website/docs/llms/openrouter.md
aider/website/docs/llms/other.md

Also replace all occurrences in the documentation to avoid confusion.
For future reference, macOS replace `find`/`sed` call ->
```shell
find . -name "*.md" -type f -exec sed -i '' 's/aider --models/aider --list-models/g' {} +
```
aider prompt to create the alias without knowing anything about the code base:
```
/ask Where do I have to look when I want to give a configuration / command line option an alias, e.g. `--list-models` should be an alias for `--models`? 
```

Add --list-models alias for --models

---

aider/models.py

Here are some small internal configuration changes for you to consider:
- enable prompt caching on OpenRouter for Sonnet-3.5
- could also be enabled for Opus, but since it is not for direct API via Anthropic I waited with this change, seems like no one is using that model anyway?
- remove unnecessary `"anthropic-beta"` HTTP header for 8k output since this feature is no longer beta
- OpenRouter do not need any `"anthropic-beta"` HTTP header
- updated Vertex AI `max_tokens` size for Sonnet-3.5 since this feature it is GA and available by default there
Also a `.aider.model.metadata.json` is need for correct cost calculation currently ->
```json
{
"openrouter/anthropic/claude-3.5-sonnet": {
"max_tokens": 4096,
"max_input_tokens": 200000,
"max_output_tokens": 4096,
"input_cost_per_token": …
```

Enable prompt caching for OpenRouter

---

aider/linter.py

Show a nice error message instead of crashing if the lint command cannot be executed for some reason.
fix #1376

fix: handle OSError when executing lint command

---

HISTORY.md
aider/website/HISTORY.md
aider/website/docs/ctags.md
aider/website/docs/faq.md
aider/website/docs/troubleshooting/edit-errors.md
aider/website/examples/README.md
requirements/requirements.in
tests/basic/test_editblock.py

% `codespell --ignore-words-list=assertin --skip="*.svg" --write-changes`
* https://pypi.org/project/codespell

Fix typos discovered by codespell

---

aider/website/_data/edit_leaderboard.yml

Recently released Qwen2.5-coder:7b-instruct-q8_0 results, which use the same architecture as Qwen2.
Note that the Qwen team said they will release a 32B coding model soon as well.
Tested with:
- Latest Ollama (0.3.11)
- `Qwen2.5-coder:7b-instruct-q8_0` model with hash `7f83705f49dd`
- Aider's dirty hash is caused only by `docker.sh` modification for `OLLAMA_API_BASE`
- It shows about 100 TPS on a single RTX4090 GPU.
The following is the `diff` format result, which is not included in this PR:
```
- dirname: 2024-09-19-15-52-54--qwen2.5-coder:7b-instruct-q8_0
test_cases: 133
model: ollama/qwen2.5-coder:7b-instruct-q8_0
edit_format: diff
commit_hash: 6f2b064-dirty
pass_rate_1: 28.6
pass_rate_2: 32.3
percent_cases_well_formed: 97.0
error_outputs: 9
num_malformed_responses: 9 …
```

Add Qwen2.5-coder:7b-instruct-q8_0 benchmark result to leaderboard

---

aider/args.py
aider/commands.py
aider/voice.py
aider/website/assets/sample.aider.conf.yml
requirements.txt
requirements/requirements.in

Add option to reduce bandwidth (and potentially latency) by converting voice recordings (wav) into a compressed audio format (webm or mp3).
Default behaviour is unchanged.
> File uploads are currently limited to 25 MB and the following input file
> types are supported: mp3, mp4, mpeg, mpga, m4a, wav, and webm.
>
> - https://platform.openai.com/docs/guides/speech-to-text
I'm a big fan of using Aider voice and noticed while using my cellphone's internet connection that it was using 10MB per minute. This reduced that to ~1MB per minute which sped up responses and reduced the rate at which I was chewing through my monthly traffic allowance.

feat: Option to compress audio files by ~90%

---

aider/io.py

This small patch ignores pressing control when pressing space.
Currently this combination makes aider hang in a special mode in `prompt-toolkit`, requiring `Ctrl-C` to get back control.

fix: add keybinding to insert space on Ctrl+Space

---

aider/main.py
tests/basic/test_sanity_check_repo.py

fix #1656 
This tiny patch adds the missing`bad_ver` variable declaration.
Since I did not see any test for the `sanity_check_repo()` function, I asked `o1-mini` to create some tests, they seem to do what they are supposed to do.
I am currently not Python literate enough and know too little about aiders's existing test infrastructure to incorporate those tests into `test_main.py`, so I left those tests in `test_sanity_check_repo.py` for now.

fix: add missing variable initialization

---

.gitignore
aider/coders/base_coder.py
aider/models.py
aider/sendchat.py

resolved: #1583 
The `extra_body` field is a parameter used by the `openai` provider.
Since `litellm` also uses this field to additionally transmit `request body`, I added a function so that `aider` can also utilize the `extra_body` field.
The `openrouter` provider also supports various functions through the additional field of `request body`, so we added the function.
The following is how to use it in model settings.
```yaml
- name: "openrouter/<YOUR_MODEL>"
edit_format: "whole"
use_repo_map: true
extra_body:
provider:
order:
- Azure
allow_fallbacks: false
```

feat: add `extra_body`field and use in model settings.

---

aider/website/docs/faq.md
aider/website/docs/usage/tips.md

fix #1758 
This adds another section in tips document about how to access past commits when starting aider new.
It may also inspire other creative usages of `/run`.

doc: Add tips for including git history in Aider chat context

---

aider/args.py
benchmark/benchmark.py

Since this help output is a bit confusing, I'd recommend to finalize the junior -> editor renames:
```shell
$ aider --help | grep -i editor
[--editor-model JUNIOR_MODEL]
[--editor-edit-format JUNIOR_EDIT_FORMAT]
--editor-model JUNIOR_MODEL
Specify the model to use for editor tasks (default
depends on --model) [env var: AIDER_EDITOR_MODEL]
--editor-edit-format JUNIOR_EDIT_FORMAT
Specify the edit format for the editor model (default:
depends on editor model) [env var:
AIDER_EDITOR_EDIT_FORMAT]
```

chore: some further junior -> editor renames

---

aider/main.py

When changing the `tool-warning-color` e.g. in the config file `~/.aider.conf.yml`
```
tool-warning-color: magenta
```
The setting was not applied
With this change, the setting is used

fix(InputOutput): apply tool warning color

---

aider/commands.py

This accomplishes two things:
1. It is now clear that /paste adds to chat from clipboard, instead of the other way around
2. /clear is now the only command starting with `cl`, making it easier to complete unambiguously

feat: rename /clipboard to /paste

---

CONTRIBUTING.md
aider/commands.py
aider/website/docs/faq.md
aider/website/docs/usage/commands.md

Here are some small documentation fixes for you to consider:
- point out that `/git` output is not included in the chat history in the help text
- add a small tip to the FAQ that `/git` will not work to include the git history/diffs
- add the `jekyll serve` command to the contributing guide (I had to look that up)
- prettier share transcript instructions in the FAQ
- fix /paste entry in docs/usage/commands.html spilling into new line

doc: small fixes

---

aider/website/_posts/2024-09-26-architect.md

Hotfix for this problem:
(via -> https://discord.com/channels/1131200896827654144/1131200896827654149/1289976901393453066)
Fixed version:

doc: hotfix for Full results table

---

aider/prompts.py

fix #1851
Commit prompt based on  this [shell function](https://gist.github.com/fry69/4e86172691a30cfb9fb77047026a0d61), which never let me down so far with Haiku.

fix: enhance commit prompt to ensure one-line with Haiku

---

aider/models.py

Add self-moderated Sonnet-3.5 OpenRouter endpoint to model list to enable e.g. prompt caching.

fix: add OpenRouter Sonnet-3.5 beta/self-moderated model

---

aider/website/_includes/multi-line.md
aider/website/docs/config/adv-model-settings.md

See title.
Includes doc fixes for the last emergency OpenRouter weak model fix.

doc: fix leftover /clipboard mention

---

aider/website/docs/install/pipx.md
aider/website/docs/llms/bedrock.md

This change hopefully avoids confusion like in #1582. (I faced the same issue 😄)

docs: update instructions for AWS Bedrock pipx installation to include boto3 inject step

---

aider/io.py

Before: it's not easy to tell what is in the context (filenames get truncated, and even when they don't it is difficult to read long paths because the most important part is at the end of a variable-length string), read-only files are not identifiable from the context shown.
```
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> /add src/backend/base/langflow/base/chains/model.py src/backend/base/langflow/base/document_transformers/model.py src/
backend/base/langflow/base/embeddings/model.py
Added /home/jonathan/Projects/langflow/src/backend/base/langflow/base/document_transformers/model.py to the chat
Added /home/jonathan/Projects/langflow/src/backend/base/langflow/base/chains/model.py to the chat
Added …
```

add format_files_for_input and compute_minimal_fileids to beautify the shown session context

---

aider/commands.py
tests/basic/test_commands.py

Looks like a bug with this Note: in-chat filenames are always relative to the git working dir, not the current working dir.
```bash
➜  aider-pull-2126 git:(main) tree
.
└── subdir
└── test_read_only_file.txt
2 directories, 1 file
➜  aider-pull-2126 git:(main) cd subdir
➜  subdir git:(main) aider
────────────────────────────────────────────────────────────────────────────────────
Update git name with: git config user.name "Your Name"
Update git email with: git config user.email "you@example.com"
Add .aider*, .env to .gitignore (recommended)? (Y)es/(N)o [Yes]: n
Aider v0.60.0
Main model: anthropic/claude-3-5-sonnet-20241022 with diff edit format, infinite output
Weak model: claude-3-haiku-20240307
Git repo: ../.git with 1 files
Repo-map: using 1024 tokens, auto refresh
Use /help <question> …
```

fix: Impossible to /read-only from another working directory

---

aider/models.py

This PR aims to
- Resolve #2179.
- Configured all models containing `o1-` to apply specific settings.
It is possible to address this issue by applying settings similar to those implemented at
https://github.com/Aider-AI/aider/blob/ed4ad45e3d7114d129eff32afcd260044ea07fdb/aider/models.py#L537-L632
for all currently available  o1 models, namely:
- azure/o1-mini,
- azure/o1-mini-2024-09-12,
- azure/o1-preview,
- azure/o1-preview-2024-09-12,
- o1-mini,
- o1-mini-2024-09-12,
- o1-preview,
- o1-preview-2024-09-12,
- openai/o1-mini,
- openai/o1-mini-2024-09-12,
- openai/o1-preview,
- openai/o1-preview-2024-09-12,
- openrouter/openai/o1-mini,
- openrouter/openai/o1-mini-2024-09-12,
- openrouter/openai/o1-preview, and
- openrouter/openai/o1-preview-2024-09-12.
However, this method involves …

Configure o1 model settings to date-stamped versions

---

aider/models.py

This PR duplicates `anthropic/claude-3-5-sonnet-20241022` as `bedrock/anthropic.claude-3-5-sonnet-20241022-v2:0`, and `anthropic/claude-3-5-haiku-20241022` as `bedrock/anthropic.claude-3-5-haiku-20241022-v1:0`.
It appears as though AWS Bedrock honours the extra headers for prompt caching, etc on the base Anthropic model configurations!
It might make sense to find a way to deduplicate this file in the future.

Add Sonnet & Haiku ModelSettings for Bedrock

---

aider/website/_data/edit_leaderboard.yml

The Qwen team still calls it Qwen2.5, but as can be seen from the benchmarks the difference in performance compared to the old weights is pretty substantial. The GGUF version of this model made by Bartowski calls it 2.5.1 to differentiate it from the earlier version of the same model.

Added Qwen2.5-7b-coder with the updated weights

---

aider/coders/base_coder.py

This corrects a grammatical error in the system prompt within `base_coder.py`. The `language` variable was previously set as:
language = "in the same language they are using"
Which resulted in the prompt:
"Always reply to the user IN IN the same language they are using."

fix: Correct typo in base_coder by removing duplicate 'in'

---

aider/coders/base_coder.py

Currently if aider outputs something like `Shall we look at the contents of 'workers/routes.ts'?`, it does not ask if we want to add the file to the chat because it ends with a question mark. This fixes that.

Add '?' to set of punctuations to strip for file mentions

---

aider/args.py
aider/website/docs/config/options.md

The `--code-theme` configuration option can accept any of the [Pygments builtin styles](https://pygments.org/styles/) (see [#49](https://github.com/Aider-AI/aider/pull/49)). I had to dig into the source to discover this, so this PR simply makes that better-documented for users.

Document that Pygments styles can be used for --code-theme

---

aider/main.py

When I start up aider I get:
```
Add .env to .gitignore (recommended)? (Y)es/(N)o [Yes]:
```
This is despite me not actually having a `.env` to ignore. I have to click through this every time I start aider, and it's annoying. This prompts to add the file only if it exists.

Don't add .env to gitignore when it doesn't exist.

---

aider/main.py
tests/basic/test_sanity_check_repo.py

Added error handling for UnicodeDecodeError when decoding paths in the Git repository. This issue arises when paths are encoded in formats other than the expected system encoding.
The error handler now provides a detailed error message, helping users identify potential encoding mismatches.
Closes #1802

Fix issue #1802: Handle UnicodeDecodeError in repo file paths

---

.gitignore
benchmark/Dockerfile

This PR addresses the Rosetta errors encountered when running Go benchmarks on Apple Silicon Macs. It modifies the benchmark Dockerfile to install the correct architecture-specific version of Go and adds tmp.benchmarks to .gitignore.                                                       
- Added architecture detection in Dockerfile to install correct Go binary:                                                                                                                                                                                                                      
- Uses arm64 version on Apple Silicon/aarch64 …

Fix Go installation and benchmark tests for Apple Silicon

---

benchmark/Dockerfile

Fixes an issue where the cacerts directory isn't created before openjdk-21-jdk is installed in the benchmarks docker container.
Ran into this while following the benchmark instructions at https://github.com/Aider-AI/aider/blob/main/benchmark/README.md.
My setup was a fresh install of Docker with Rosetta 2 on macOS and a fresh clone of aider.
<details>
```shell
124.4 Setting up ca-certificates-java (20190909ubuntu1.2) ...
124.4 head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory
124.4 #
124.4 # A fatal error has been detected by the Java Runtime Environment:
124.4 #
124.4 #  SIGILL (0x4) at pc=0x0000ffff97c67c5c, pid=3573, tid=3574
124.4 #
124.4 # JRE version:  (21.0.5+11) (build )
124.4 # Java VM: OpenJDK 64-Bit Server VM (21.0.5+11-Ubuntu-1ubuntu122.04, …
```

Install ca-certificates before openjdk-21 to resolve cacerts error

---

aider/website/docs/llms/bedrock.md

The solutions provided in the documentation for installing the missing `boto3` library do not work with a one-liner install script or UV. In this note, I propose additional information about the installation process.

Document boto3 install process with aider installed by uv or one-liner

---

aider/website/_data/polyglot_leaderboard.yml

This commit adds the evaluation results of `Qwen2.5-Coder-32B-Instruct` on the Polyglot benchmark with the `whole` edit format.

Polyglot Qwen2.5-Coder-32B-Instruct Results [Whole]

---

aider/repo.py

Gracefully handle repos with index errors.
- skips any directories with indexing issues

Ignore directories in repo that have index errors

---

benchmark/benchmark.py

`.discard()` removes an item from the set. `.difference_update()` is the correct call here.

Fix files not being excluded in benchmark.py

---

aider/website/docs/usage/watch.md

noted that the docs description wasn't relevant to the IDE / --watch-files docs
apparently my editors markdown formatter applied to this doc, let me know if that's an undesirable change and i can redo this to only affect the description line

Improve description of watch.md

---

aider/args.py
aider/io.py
aider/main.py

Add configurable line endings for file writes
As discussed in: https://github.com/Aider-AI/aider/issues/1102 
Previously, aider always wrote files with platform-specific line endings on Windows,
which made it impossible for Windows users to maintain files with LF line endings.
Added a new --line-endings argument that controls how files are written:
- `platform` (default): Use system default (\n on Unix, \r\n on Windows)
- `lf`: Always use \n
- `crlf`: Always use \r\n
Comment:
- `InputOutput.read_text` always converts line endings to `\n` (LF) implicitly. I did not touch that behaviour.
- `InputOutput.write_text` previously always wrote platform dependent line endings (which can cause problems). The new `line_endings` configuration default (`platform`) preserves the original behavior, but …

feat: Add line endings configuration option for file writing - fixes #1102

---

aider/sendchat.py

Currently, as of aider 0.72.2, if deepseek/deepseek-reasoner (aka 'r1') is selected as the model and ^C is used to cancel a request, then you may end up in a situation where you have two user requests in a row, and the model will refuse to process requests.  This short patch runs a check immediately before submission to ensure the messages alternate roles between 'user' and 'assistant', inserting a message of the appropriate role and an empty string for content to prevent the model from rejecting the request.  The assumption is that since submission is done infrequently, the expense is minimal to so on every request.
The error this patch resolves appears as follows:
```
litellm.BadRequestError: DeepseekException - Error code: 400 - {'error': {'message': 'deepseek-reasoner does not support …
```

Ensure alternating roles for deepseek-reasoner

---

aider/website/docs/llms/deepseek.md

This pull request includes a small update to the `aider/website/docs/llms/deepseek.md` file. The change updates the references to the DeepSeek model to reflect the latest version.
* Updated references from "DeepSeek Coder V2" to "DeepSeek Chat V3" to reflect the latest model in the documentation.
xref: https://aider.chat/docs/leaderboards/

docs: update DeepSeek v2 Coder to v3 Chat

---

aider/website/docs/config/adv-model-settings.md

Setting the `extra_body` as suggested by the doc gives me the following error:
```
Error loading aider model settings: Error loading model settings from /home/zhyu/.aider/aider.model.settings.yml: ModelSettings.__init__() got an unexpected keyword
argument 'extra_body'
```
Setting `extra_body` as a key of `extra_params` fixed the issue for me. And I confirmed that the behavior changed accordingly after I set the reasoning effort for o1 in this way.
It also matches another `extra_body` usage in this [doc](https://aider.chat/docs/llms/openrouter.html#controlling-provider-selection).

Fix docs regarding extra_body

---

aider/resources/model-metadata.json
aider/resources/model-settings.yml

Considering Deepseek's recently down, Fireworks has been the most reliable backup lately. Could be useful to those who want to keep using Deepseek.

Add `fireworks_ai/deepseek` models

---

aider/repo.py

Found a misspelling.
https://github.com/crate-ci/typos

Correct a typo

---

aider/special.py

Now that aider supports Kotlin syntax, this change will allow for indexing of kotlin-based gradle project files

fix: add build.gradle.kts to special.py

---

aider/commands.py

```
Approximate context window usage for openrouter/anthropic/claude-3.5-sonnet, in tokens:
$ 0.0059    1,976 system messages          
$ 0.0108    3,597 repository map           use --map-tokens to resize
$ 0.0001       30 aider/__main__.py        /drop to remove
$ 0.0003       92 aider/help_pats.py       /drop to remove
$ 0.0004      135 aider/__init__.py        /drop to remove
$ 0.0004      136 aider/watch_prompts.py   /drop to remove
$ 0.0006      193 aider/dump.py            /drop to remove
$ 0.0008      274 aider/format_settings.py /drop to remove
$ 0.0009      285 aider/llm.py             /drop to remove
$ 0.0009      313 aider/urls.py            /drop to remove
$ 0.0012      413 aider/copypaste.py       /drop to remove
$ 0.0016      533 aider/prompts.py         /drop to remove
$ …
```

refactor: Sort files by token count in cmd_tokens

---

tests/basic/test_editor.py

The test for `EDITOR` preference failed to clean up any existing value of `VISUAL` which may be present in the environment pytest is run in.
For example, on my laptop I have `VISUAL` set to `nano`, and the test would fail with:
```python
def test_get_environment_editor():
with patch.dict(os.environ, {}, clear=True):
assert get_environment_editor("default") == "default"
with patch.dict(os.environ, {"EDITOR": "vim"}):
>           assert get_environment_editor() == "vim"
E           AssertionError: assert 'nano' == 'vim'
E             
E             - vim
E             + nano
tests/basic/test_editor.py:25: AssertionError
```

Fix test for `get_environment_editor()`

---

aider/website/docs/llms/lm-studio.md

There are a few small gotchas when configuring LM Studio to work with aider. This adds a few clarifying instructions to the documentation.

Add clarifying instructions to LM Studio config

---

HISTORY.md
aider/resources/model-metadata.json
aider/resources/model-settings.yml
aider/website/HISTORY.md
aider/website/docs/config/adv-model-settings.md

Support for DeepSeek V3 (Free) via OpenRouter, see [https://openrouter.ai/deepseek/deepseek-chat:free](https://openrouter.ai/deepseek/deepseek-chat:free).

Adding OpenRouter deepseek-chat:free (V3)

---

aider/main.py
aider/repo.py

Fixes #2668 (and #1085). 
By using `git-config` command, both local and global git settings will be considered. 
I don't know what to do with the fallback identity. I have left it as it is. If either user or email is unavailable from any of the git configs, aider will still set the fake identity.

Retrieve the identity using git-config command

---

requirements/common-constraints.txt
requirements/requirements-dev.in
requirements/requirements-dev.txt

`uv` is used in `pip-compile.sh`, so this PR adds it as a dev dependency.

fix: add uv as development dependency

---

aider/watch.py

This PR addresses an issue where Aider fails to launch due to `PermissionError`.
In monorepos or complex repository configurations, permission errors can occur due to reasons such as Docker volume mounts.
In some cases, these errors are unavoidable, so this PR proposes that `PermissionError` can be safely ignored.

refactor: add ignore_permission_denied option to watch function

---

benchmark/README.md

Use a consistent clone url to help those who don't use ssh with GitHub.  This should not break for those who do.

Update Benchmark README.md

---

aider/io.py

When vi-mode is enabled, there are two modes as usual in vi:
- Insert mode where text can be entered. 
- Normal mode where text can be edited (for example delete word under cursor) but not inserted unless switching to insert-mode. 
When multiline-mode is enabled, currently pressing enter while in normal mode also results in entering a new line. This is unusual behavior in vi-mode. Usually, in such a case the command is sent, which makes sense considering the context where this happens.
I think most vi-users would prefer if in multiline-mode a new line is only added in insert-mode, and in normal-mode the command is sent. This PR fixes this.

feat: vi-like behavior when pressing enter in multiline-mode

---

aider/args.py

This PR fixes a bug in aiderignore path specification.
Currently, when aiderignore is configured, aider tries to find aiderignore from the relative path where aider was started.
This PR corrects this behavior so that aiderignore is searched for using a relative path from the git root, similar to gitignore.
solve #3422

refactor: enhance --aiderignore argument to resolve absolute and relative paths

---

aider/models.py
tests/basic/test_aws_credentials.py

Even if I set `AWS_PROFILE` in my `~/.env`, i got warning that i
didn't set environment variables properly if i don't set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`. But with ignoring it, i can
use Claude 3.7 from AWS bedrock without any issue.
```
Warning: us.anthropic.claude-3-7-sonnet-20250219-v1:0 expects these environment variables
- AWS_ACCESS_KEY_ID: Not set
- AWS_SECRET_ACCESS_KEY: Not set
You can skip this check with --no-show-model-warnings
```
- No such warning shown
1. In `aider/models.py`, code was added to check if AWS_PROFILE is set when AWS credential keys are missing and the model is a Bedrock model (starting with "bedrock/" or "us.anthropic."). If AWS_PROFILE is set, it removes AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY from the list of missing keys, effectively …

fix: Redundant warning when `AWS_PROFILE` set for Bedrock

---

aider/mdstream.py

improves markdown header rendering for better reading flow.
before, center aligned:
after, left aligned:
references:
- https://discord.com/channels/1131200896827654144/1354844311216324711

Align markdown headings to the left

---

aider/linter.py

In, for example, Next.js projects, certain paths must contain components with filenames containing shell metacharacters, such as app/(auth)/login.ts for example.  These paths must be quoted for the shell to do the right thing and interpret those characters literally.  
Without this tiny patch, try to run the linter on such files results in an errror.  With this patch, it invokes the command with the files correctly.
This is a general issue, and shlex.quote implements a solution designed to be portable across shells.  It may be possible to craft a malicious filename to circumvent it on non-Unix hosts, according to the docs, but quoting it at all seems to be a step in the right direction -- this does not add to that class of vulnerability.

fix: Use shlex.quote() to enable linting filepaths containing shell metacharacters

---

aider/io.py

This PR fixes an issue where the `completion-menu-current-color` and `completion-menu-current-bg-color` properties were incorrectly applied.
Previously:
- `completion-menu-current-color` was setting the background color
- `completion-menu-current-bg-color` was setting the text color
This was backwards from the expected behavior and from how prompt_toolkit's default styling works (where `fg` sets text color and `bg` sets background color).
The fix 
- Swapped the color assignments so:
- `completion-menu-current-color` now properly sets the text color
- `completion-menu-current-bg-color` now properly sets the background color
This matches prompt_toolkit's default styling pattern seen in defaults.py:
```python
("completion-menu.completion.current", "fg:#888888 bg:#ffffff reverse")
```
Now …

Correct completion menu current item color styling

---

aider/onboarding.py

1. The module already imports `requests`, so by the time this check is called, the module is already loaded.
2. Even if the code path were taken, it would fail anyway, because the `aider[oauth]` extra was hallucinated and does not exist.
3. Downstream distributions usually have managed Python environments, where pip cannot be used at all.
That means distros must patch out every such pip invocation ([example](https://aur.archlinux.org/cgit/aur.git/tree/archlinux-use-system.patch?h=aider-chat&id=7f8156946857215104bce151454ad0101ade4a48); full disclosure: I maintain this but other distros will eventually bump into the same issues).  
Restricting at-runtime pip usage to the minimum necessary is friendlier to distro maintainers.

chore: remove redundant code

---

aider/resources/model-metadata.json
aider/resources/model-settings.yml

Fireworks supports the recently released `deepseek-v3-0324` model.
https://fireworks.ai/models/fireworks/deepseek-v3-0324
**Note:** I couldn't verify the `max_input_tokens` and `max_output_tokens` values, as this information isn't available on their homepage. I assume these values remain the same as those for the existing `deepseek-v3` model.

Add Fireworks AI model 'deepseek-v3-0324'

---

aider/website/_includes/multi-line.md

I've just discovered that as I can in my bash (as I configured in .bashrc) press ctrl+x ctrl+e to edit in `$EDITOR`  command line(s) before execution, that it also works in Aider! So I do not have to come back to beginning of prompt and add `/editor` anymore! (what is especially annoying in multi line `{` mode etc...) . It's life changer ! :) So IMHO should be communicated somehow in documentation to people that this also works in Aider prompt!
---
* Added keybinding `Ctrl-X Ctrl-E` for invoking editor via terminal compatibility.
* Enhances user ergonomics for terminals supporting this shortcut, streamlining workflow.
* Maintains reference to editor configuration documentation.

docs: update editor usage instructions in multi-line guide

---

aider/coders/editblock_coder.py
tests/basic/test_editblock.py

Fixed these issues:
[3785](https://github.com/Aider-AI/aider/issues/3785)
[3811](https://github.com/Aider-AI/aider/issues/3811)
[3793](https://github.com/Aider-AI/aider/issues/3793)
The root of the problem was that the match for `<<<<<<< SEARCH` only matched the line below \`\`\`. However, diff-fenced is two lines below \`\`\`. Therefore, by matching one more line, it solves the issue of edits being incorrectly identified as commands.

fix: correctly detect edit blocks in diff-fenced mode

---

aider/io.py

First of all, thanks a lot for Aider — it's an amazing tool and has been super helpful!
When using `C-x C-e` to edit the current input in an external editor, the temp file didn't have a suffix.
Now it sets `suffix="md"` when calling `pipe_editor`, so editors like vim can pick up Markdown syntax highlighting.
Editing without a file suffix makes it harder for editors to guess the right language mode.
Adding `.md` improves the editing experience.
Also, the `/editor` command already uses a `.md` suffix — this change brings `C-x C-e` in line with that.
- Only affects the temp file name when opening the editor
- Better UX for editing Markdown
- Consistent behavior between `C-x C-e` and `/editor`

fix: add suffix "md" when opening editor in InputOutput class

---

aider/website/_includes/blame.md

I was always curious when the inflection near release v0.45 happened.
Thus, I added dates.
It's the first time I send a PR, thus I agree to [Individual Contributor License Agreement](https://aider.chat/docs/legal/contributor-agreement.html).

Show dates on "Release history" chart

---

aider/website/docs/usage/lint-test.md

This makes the example script more safely handle file paths. See https://www.shellcheck.net/wiki/SC2086.

docs: update lint/test pre-commit shell script example to use "$@" for proper argument handling

---

aider/args.py
aider/commands.py
tests/scrape/test_playwright_disable.py

This PR introduces a new command-line argument `--disable-playwright` to address user requests for a way to prevent Aider from prompting for Playwright installation or attempting to use it for web scraping.
**Problem:**
Users, particularly those running Aider in automated environments or on operating systems not supported by Playwright, found the repeated prompts to install Playwright disruptive (as reported in #3765). Even with `--yes-always`, the installation process could hang waiting for sudo passwords.
**Solution:**
- Added a `--disable-playwright` flag (defaulting to `False`).
- When `--disable-playwright` is set to `True`, Aider will:
- Skip the check/prompt for Playwright installation within the `/web` command.
- Initialize the `Scraper` with `playwright_available=False`, ensuring …

feat: Add --disable-playwright flag to prevent Playwright installation and prompts

---

aider/queries/tree-sitter-language-pack/ocaml-tags.scm
aider/queries/tree-sitter-language-pack/ocaml_interface-tags.scm
aider/queries/tree-sitter-languages/ocaml_interface-tags.scm
tests/basic/test_repomap.py
tests/fixtures/languages/ocaml_interface/test.mli

Adds repo map support for .ml and .mli
Things I'm not sure about:
1. Should we have same tags files in both `queries/tree-sitter-language-pack`
`queries/tree-sitter-languages`?
2. I think we should be smarter and only use tags from .mli files if they are
present. E.g. if test.ml and test.mli are both present in the repo — get
atgs only from test.mli as this is the external interface of the `Test`
module.
Depends on:
- https://github.com/Goldziher/tree-sitter-language-pack/pull/25
- https://github.com/Aider-AI/grep-ast/pull/19

feat: add repomap support for ocaml/ocaml_interface

---

aider/gui.py
aider/scrape.py

I just discovered aider (it looks great so far!) and while exploring the installation / configuration options I ran into a problem with the scraper where it wasn't picking up any content from our SPA.
After some debugging of my playwright install I finally realized the sample command `python -m aider.scrape https://aider.chat/docs/usage/tips.html` I was referencing from [the docs ](https://aider.chat/docs/usage/images-urls.html#web-pages) would never utilize the playwright backend. This is an attempt to fix this behavior for the sample command in the docs and also for the experimental web GUI.

use playwright if available when invoking scraper via cli

---

aider/resources/model-metadata.json
aider/resources/model-settings.yml

Hello @paul-gauthier,
This PR removes the `:free` suffix from the `openrouter/google/gemini-2.5-pro-exp-03-25` model identifier in `aider/resources/model-settings.yml` and renames its corresponding entry in `aider/resources/model-metadata.json`.
This change aligns our configuration with OpenRouter's recent update, where they now alias the `:free` suffixed model ID to the standard, non-suffixed ID. Consequently, the model remains free to use via this standard ID, albeit subject to new, stricter rate limits.
https://openrouter.ai/google/gemini-2.5-pro-exp-03-25

refactor: Update OpenRouter Gemini 2.5 Pro Exp model ID

---

aider/resources/model-settings.yml

Enhancement, Configuration
___
- Reduced `max_tokens` for all `claude-opus-4-20250514` model variants to `32000`.
- Updated settings in `aider/resources/model-settings.yml` for consistency.
- Ensured all aliases and regional variants reflect the new token limit.
- No changes to other model configurations or parameters.

Change `max_tokens` to 32000 for `claude-opus-4-20250514` family model

---

aider/io.py
aider/repo.py
tests/basic/test_repo.py

Fix two issues, which prevents aider from using on repositories with single-byte encodings:
1. Fix inability to use `--llm-history-file` option when non-Unicode encoding is set by `--encoding`. Before this fix any action in aider with this options results in following error:
```
Traceback (most recent call last):
File "C:\Users\Vitya\AppData\Roaming\uv\tools\aider-chat\Lib\site-packages\aider\coders\base_coder.py", line 1454, in
send_message
yield from self.send(messages, functions=self.functions)
File "C:\Users\Vitya\AppData\Roaming\uv\tools\aider-chat\Lib\site-packages\aider\coders\base_coder.py", line 1788, in
send
self.io.log_llm_history("TO LLM", format_messages(messages))
File "C:\Users\Vitya\AppData\Roaming\uv\tools\aider-chat\Lib\site-packages\aider\io.py", line 754, in …
```

Fix issues on repositories with non-Unicode encodings

---

aider/models.py

As a few people mentioned in the #2227 issue, it is necessary to pass some `extra_headers` to Copilot with each request in order for it to work properly. Furthermore, without a specific `.aider.model.settings.yml`, the most recent patch #4092 that automatically refreshes the GH Copilot API Key does not work because it requires `extra_params` to be explicitly provided for a model; otherwise, the following error occurs:
```
File "~/code/stackbuilders/aider/aider/models.py", line 892, in github_copilot_token_to_open_ai_key
"Editor-Version": self.extra_params["extra_headers"]["Editor-Version"],
~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
This PR defines some default `extra_headers` for each model request, as well as the call to the Copilot API to …

fix: Always pass `extra_headers` to Copilot models

---

aider/args.py
aider/coders/base_coder.py
aider/commands.py
aider/main.py
aider/website/docs/config/options.md
tests/basic/test_main.py

- Fixed the file processing logic in base_coder.py to properly skip gitignored files when specified on the command line
- Added a new --add-gitignore-files flag to control whether gitignored files should be included
- Added tests for command line and /add command behavior
$ echo "ignored.txt" > .gitignore
$ touch ignored.txt
$ aider ignored.txt
Skipping /path/to/ignored.txt that matches gitignore spec.
Added ignored.txt to the chat. # Inconsistent behavior
\> /add ignored.txt
Can't add ignored.txt which is in gitignore # Correct behavior
$ echo "ignored.txt" > .gitignore
$ touch ignored.txt
$ aider ignored.txt
Skipping /path/to/ignored.txt that matches gitignore spec. # File is properly skipped
$ aider --add-gitignore-files ignored.txt
Added ignored.txt to the chat.

feat: Add --add-gitignore-files flag

---

aider/io.py

The inline code snippets in the reply from AI models are formatted using some default theme. They are somewhat harder to read and are just ugly.
> Let the `inline_code_theme` as used in the `rich.markdown.Markdown`'s `__init__` have effect.
But if a `inline_code_lexer` is **not** passed to `rich.markdown.Markdown`, `inline_code_theme` is not being used to style inline code, as evident in the `__init__` of `rich.markdown.MarkdownContext`. But there's no reasonably easy way to determine the programming language of inline code snippets to be able to identify the lexer. This PR's solution is to utilize the lexer `text` as the value of the `inline_code_lexer` passed to `Markdown`. In this scenario "rich" uses `code_theme` as the fallback value for `inline_code_theme`

Let 'rich' use code_theme as inline_code_theme

---

aider/resources/model-settings.yml

If I call `aider --model vertex_ai/gemini-2.5-pro-preview-05-06`, the default for the weak model is incorrect. It'll say print this error when making a commit message:
```
litellm.BadRequestError: LLM Provider NOT provided. 
Pass in the LLM provider you are trying to call. 
You passed model=vertex_ai-language-models/gemini-2.5-flash-preview-04-17
Pass model as E.g. For 'Huggingface' inference endpoints pass in 
`completion(model='huggingface/starcoder',..)`
Learn more: https://docs.litellm.ai/docs/providers
```
I think this is the fix - it replaces `vertexai-language-models/` with `vertexai/`

fix: Correct Vertex AI model name prefixes in settings

---

aider/args.py
aider/commands.py
aider/models.py
aider/website/assets/sample.aider.conf.yml
aider/website/docs/config/options.md
aider/website/docs/config/reasoning.md
aider/website/docs/usage/commands.md

Once you run `/thinking-tokens 4k` inside chat, there was no way to reset it. With this PR, `/thinking-tokens 0` does that.

[Feature] Resetting thinking tokens using "0"

---

aider/analytics.py
aider/args.py
aider/main.py
aider/website/assets/sample.aider.conf.yml
aider/website/docs/more/analytics.md

Hi! 👋🏻
Would you consider adding configuration options to specify a custom PostHog project or a custom PostHog host?
This could be helpful for teams using aider within a company who want to monitor adoption and usage among engineers using their own PostHog setup.
Thanks for considering it!

feat: add configurable PostHog host and API key parameters

---

aider/history.py

The update in history.py (summarize_real) includes = >
1. Eliminate list reversals and streamline token summation
2. Refactor head slicing: iterate directly over sized_head for speed
3. Improve performance of message splitting by removing unnecessary reversals.
I think it will make it bit faster as per my exp..

Optimize head‑truncation loop in summarize_real()

---

aider/resources/model-metadata.json
aider/resources/model-settings.yml

Overall documentation is quite light for this new model.
Max token information is from https://openrouter.ai/moonshotai/kimi-k2.
Information regarding the ideal temperature (0.6) and use of system prompt is from https://platform.moonshot.ai/docs/guide/agent-support ; although this is fairly standard. 
**Moonshot AI mention poor performance on one-shot style prompts, might be worth tweaking settings based on this.**
Using:
```
examples_as_sys_msg: true
```
is a best guess on my part based on a guessed similarity to R1.
Partially addresses #4341 , however adding Moonshot AI platform API support will probably need to be addressed by litellm.

Add openrouter kimi-k2 model to `aider/resources`.

---

aider/queries/tree-sitter-languages/julia-tags.scm

added a new tags.scm file for Julia.
Implements semantic tags for Julia constructs including:
- Functions (named and anonymous)
- Macros
- Modules
- Structs / mutable structs
- Constants & variables
This makes it easier to navigate Julia codebases

added julia tree sitter

---

aider/resources/model-settings.yml

Support for Bedrock/Claude 4.5.
Announced here:
https://aws.amazon.com/blogs/aws/introducing-claude-sonnet-4-5-in-amazon-bedrock-anthropics-most-intelligent-model-best-for-coding-and-complex-agents/
Proposed model name:
bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0
Fixes: https://github.com/Aider-AI/aider/issues/4543
#4543

Feature request: support for Bedrock/Claude 4.5 
